config/routes.rb
SampleApp110811::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only =>[:create, :destroy]
  resources :groups, :only => [:create, :destroy]

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/group.rb
class Group < ActiveRecord::Base
  
  attr_accessible :leader_id
  
  belongs_to :follower, :foreign_key => "follower_id", :class_name => "User"
  belongs_to :leader,   :foreign_key => "leader_id", :class_name => "User"
  
  validates :follower_id, :presence => true
  validates :leader_id, :presence => true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  
  attr_accessible :content
  belongs_to :user
  
  validates :content, :presence => true,
                      :length => { :maximum => 150}
  
  validates :user_id, :presence => true
                      
  default_scope :order => 'microposts.created_at DESC'
  
  self.per_page = 10

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :name, :email
  
  has_many :microposts
  
  has_many :groups, :foreign_key => "follower_id"
  
  has_many :following, :through => :groups, :source => :leader
  
  has_many :reverse_groups, :foreign_key => "leader_id",
                            :class_name => "Group"
                                   
  has_many :followers, :through => :reverse_groups, 
                       :source => :follower
  
  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50}
  
  validates :email, :presence => true,
                    :format   => { :with => email_regexp},
                    :uniqueness => {:case_sensitive => false}
                    
  self.per_page = 10
                    
  def following?(leader)
    groups.find_by_leader_id(leader)
  end
  
  def follow!(leader)
    groups.create!(:leader_id => leader.id)
  end
  
  def unfollow!(leader)
    groups.find_by_leader_id(leader).destroy
  end
  
  def self.authenticate(email)
     user = find_by_email(email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate

  def create
    user = User.find_by_email(params[:group][:leader_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Group.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
 
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      render 'pages/home'
    end
  end

  def destroy
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
       @micropost = Micropost.new
    end
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user.nil?
      flash.now[:error] = "Invalid email"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
     sign_out
     redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  
  def new   # responds to get /users/new by rendering new.html.erb
    @title = "Sign up"
    @user = User.new
  end
  
  def create  # responds to post /users and redirects to /user/i if successful or new.html.erb if not
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_path(@user)
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def show  # responds to get /user/i by rendering show.html.erb
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page] )
    @title = @user.name
  end
  
  def index  # responds to get /users by rendering index.html.erb
    @title = "Current users"
    @users = User.paginate(:page =>params[:page])
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(:page =>params[:page])
    render 'show_follow'
  end
  
   def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  private
     def authenticate
       deny_access unless signed_in? 
     end
     
     def correct_user
       @user = User.find(parms[:id])
       redirect_to(root_path) unless current_user?(@user)
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    image_tag("logo.png", :alt => "Kays App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.email
    current_user = user
  end
  
  def sign_out
    cookies.delete(:remember_token)
    current_user= nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
      !(current_user.nil?)
  end
  
  def authenticate
     deny_access unless signed_in?
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end

  private
    def user_from_remember_token
      userEmail = remember_token
      User.find_by_email(userEmail)
    end
  
    def remember_token
      cookies[:remember_token] || nil
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
 <footer>
	<nav class = "round" >
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", 'http://news.railstutorial.org' %></li>
			<li><%= link_to "Rails tutorial", 'http://railstutorial.org' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class ="round" >
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<% if signed_in? %>
			  <li><%= link_to "Users", users_path %>
			  <li><%= link_to "Profile", current_user %> </li>
			  <li><%= link_to "Sign out", signout_path %> </li>
			<% else %>
			   <li><%= link_to "Sign in", signin_path %> </li>
			<% end %>
	    </ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag    'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag    'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @title %></title>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
   </head>
   <body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
				   <div class="flash <%= key %>">
					   <%= value %>
				   </div>
				<% end %>
				<%= yield %>
			</section>
           <%= render 'layouts/footer' %>
        </div>
   </body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
<td class="micropost">
<span class="content"><%= micropost.content %></span>
<span class="timestamp">
Posted <%= time_ago_in_words(micropost.created_at) %> ago.
<span>
</td>
</tr>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if signed_in? %>
<h1 class="micropost">What's up?</h1>
<%= render 'shared/micropost_form' %>
<%= render 'shared/user_info' %>
<%= render 'shared/stats.html.erb'%>
<% else %>
<%= link_to "Sign up now!", new_user_path, :class => "signup_button round" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <div class="field" >
    <%= f.text_area :content %>
  </div>
  
  <div class="actions" >
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<h3>User stats</h3>
	<table>
		<tr>
			<td>
				<a href="<%= following_user_path(@user) %>">
			    <span id="following" class="stat">
			    	<%= @user.following.count %> following
			    </span>
            </td>
		</tr>
		<tr>
			<td>
				<a href="<%= followers_user_path(@user) %>">
			    <span id="followers" class="stat">
			    	<%= pluralize(@user.followers.count, "follower") %> 
			    </span>
            </td>
		</tr>
    </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>" >
		<span class="user_name">
		<%= current_user.name %>
		</span>
		<span class="microposts">
		   <%= pluralize(current_user.microposts.count, 'micropost') %>
		</span>
	</a>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.groups.
  build(:leader_id => @user.id)) do |f| %>
  <div>
  	<% f.hidden_field :leader_id %>
  	<div class="actions">
  		<%= f.submit "Follow" %>
  	</div>
  </div>

<% end %>

app/views/users/_follow_form.html.erb
<h3>Follow button should be here</h3>
<% unless current_user?(@user) %>
<div id=follow_form>
	<% if current_user.following?(@user) %>
	   <% render 'unfollow' %>
	<% else %>
	   <% render 'follow' %>
    <% end %>
</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.groups.find_by_leader_id(@user), :html => { :method => :delete } do |f| %>
 
  	<div class="actions">
  		<%= f.submit "Unfollow" %>
  	</div>


<% end %>

app/views/users/_user.html.erb
<li><%= link_to user.name, user %></li>

app/views/users/index.html.erb
<h1>Current users</h1>


<%= will_paginate %>

<ul>
<% @users.each do |user| %>
  <li><%= link_to user.name, user %> 
      <%= user.email %>
  </li>
<% end %>
</ul>

<%= will_paginate %>
<br />

<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for(@user) do |f| %>
  <div class="field" >
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
  
  <div class="field" >
    <%= f.label :email %> 
    <%= f.text_field :email %>
  </div>
  
  <div class="actions" >
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>Find me in app/views/users/show.html.erb</p>

<p> <strong>Email:</strong> <%= @user.email %></p>

<%= render 'shared/stats' %>

<%= render 'follow_form' if signed_in? %>
<hr/>
<p> <strong>Number of microposts:</strong> <%= @user.microposts.count %></p>

<% unless @user.microposts.empty? %>
<div class="micropost-lists">
<h2>Microposts</h2>
<table>
<%= render @microposts %>
</table>
<%= will_paginate @microposts %>
</div>
<% end %>

<hr/>


<%= link_to 'Home',  root_path %>

<%= debug(params) if Rails.env.development? %>

app/views/users/show_follow.html.erb
<h1><%= @title %> </h1>

<% unless @users.empty? %>
<ul>
	 <%= render @users %>
</ul>
<%= will_paginate @users %>
<% end %>